name = "hato-status"
main = "src/worker.ts"
compatibility_date = "2023-05-15"

kv_namespaces = [
  { binding = "HATO_STATUS", id = "b5b568b4fc764ec093eeca473f1008ef", preview_id = "285924d956df4a66850c337eeb08b7e1" }
]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "hato-status"
database_id = "745606d8-641b-4d1c-80ae-652bec8a1066"

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["*/2 * * * *"] # * * * * * = run every minute
